/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./MAIIN4.fbx')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.foliage.geometry}
        material={materials.baked_flowers}
        position={[-0.566, 0, 0.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ropes.geometry}
        material={materials.baked_rope}
        position={[-0.566, 0, 0.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.oreada.geometry}
        material={materials.baked_oreada}
        position={[-0.566, 0, 0.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rocks.geometry}
        material={materials.baked_rocks}
        position={[-0.566, 0, 0.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={nodes.Icosphere001.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree001.geometry}
        material={materials['baked_tree.002']}
        position={[-0.566, 0, -4515.966]}
        scale={100}
      />
      <group position={[358.176, -4.389, 356.777]} scale={19.163}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_1.geometry}
          material={materials.aiStandardSurface5SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_2.geometry}
          material={materials.aiStandardSurface1SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_3.geometry}
          material={materials.aiStandardSurface2SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_4.geometry}
          material={materials.aiStandardSurface3SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_5.geometry}
          material={materials.aiStandardSurface6SG}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sketchfab_6.geometry}
          material={materials.initialShadingGroup}
        />
      </group>
      <group
        position={[-400.257, 389.026, 430.676]}
        rotation={[0.004, -1.054, 3.082]}
        scale={31.472}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.clock_low_T_clock_0.geometry}
              material={materials.T_clock}
              position={[-0.499, -0.032, -0.003]}
            />
          </group>
        </group>
      </group>
      <group
        position={[453.951, -124.113, -75.989]}
        rotation={[Math.PI, 0.234, 0]}
        scale={3986.317}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder2_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-1.493, 1.042, 0.033]}
            rotation={[0, Math.PI / 2, 0]}
            scale={0.036}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder3_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-0.309, -0.188, 1.79]}
            rotation={[-Math.PI / 2, -0.262, Math.PI / 2]}
            scale={0.036}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder4_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-0.309, 0.128, 2.94]}
            rotation={[-1.309, 0, Math.PI / 2]}
            scale={0.036}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCylinder5_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-0.086, -0.43, 2.931]}
            rotation={[Math.PI, -1.309, 0]}
            scale={0.036}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube221_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube222_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pCube223_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface7_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface8_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface6_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
      </group>
      <group position={[463.117, 68.183, -66.137]} rotation={[-Math.PI, -1.306, 0]} scale={0.325}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_default1_0.geometry}
            material={materials.default1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_page_0.geometry}
            material={materials.page}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9002.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9004.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9011.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9014.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9016.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9018.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9019.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9020.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9021.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9023.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9025.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9026.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9027.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9028.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9031.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9033.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.M_EmissiveCloud}
        position={[-113.057, 791.107, 650.517]}
        rotation={[-0.137, -0.584, -0.076]}
        scale={[217.723, 217.707, 209.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9005.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9006.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9008.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-114.322, 706.02, 648.495]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9012.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9013.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9015.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-114.322, 706.02, 648.495]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9022.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9029.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9030.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9032.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-114.322, 706.02, 648.495]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9034.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-114.322, 706.02, 648.495]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group7_pasted__sweep9035.geometry}
        material={materials.M_Staff_Diffuse}
        position={[-116.799, 706.02, 650.481]}
        rotation={[0, -0.589, 0]}
        scale={2.088}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.M_Floating_Particles}
        position={[-210.178, 758.973, 629.713]}
        rotation={[-0.425, 0.165, -0.889]}
        scale={[95.544, 45.513, 67.071]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials.M_Floating_Particles}
        position={[-200.787, 801.698, 631.861]}
        rotation={[-0.428, 0.175, -0.878]}
        scale={[53.424, 130.661, 198.112]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.M_Floating_Particles}
        position={[-165.345, 846.814, 627.437]}
        rotation={[-0.421, 0.167, -0.875]}
        scale={[70.929, 17.064, 56.088]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.M_Floating_Particles}
        position={[-88.365, 862.905, 628.047]}
        rotation={[2.718, -0.148, -2.256]}
        scale={[-97.22, 79.967, 52.675]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.M_Floating_Particles}
        position={[-40.483, 845.508, 643.703]}
        rotation={[-0.411, 0.166, -0.899]}
        scale={[102.163, 37.172, 27.879]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials.M_Floating_Particles}
        position={[-49.891, 822.604, 622.716]}
        rotation={[-0.432, 0.184, -0.868]}
        scale={[69.02, 14.22, 26.545]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials.M_Floating_Particles}
        position={[-75.686, 768.272, 720.082]}
        rotation={[-0.422, 0.165, -0.882]}
        scale={[97.966, 78.786, 193.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials.M_Floating_Particles}
        position={[-121.598, 734.063, 670.94]}
        rotation={[2.724, -0.168, -2.253]}
        scale={[-56.57, 29.517, 7.969]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials.M_Floating_Particles}
        position={[-204.146, 759.722, 612.993]}
        rotation={[-0.433, 0.194, -0.87]}
        scale={[106.568, 121.214, 176.208]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials.M_Floating_Particles}
        position={[-172.876, 850.016, 569.433]}
        rotation={[-0.415, 0.181, -0.885]}
        scale={[100.732, 128.596, 96.377]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials.M_Floating_Particles}
        position={[-153.253, 819.393, 612.536]}
        rotation={[-0.425, 0.181, -0.866]}
        scale={[96.296, 14.491, 102.327]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials.M_Floating_Particles}
        position={[-96.675, 782.226, 678.901]}
        rotation={[-0.426, 0.147, -0.892]}
        scale={[51.051, 114.491, 29.777]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials.M_Floating_Particles}
        position={[-100.838, 727.193, 635.972]}
        rotation={[-0.411, 0.169, -0.896]}
        scale={[105.512, 77.931, 119.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.M_Floating_Particles}
        position={[-62.311, 801.697, 651.345]}
        rotation={[-0.433, 0.194, -0.87]}
        scale={[106.568, 121.214, 176.208]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.M_Floating_Particles}
        position={[-96.804, 807.039, 613.346]}
        rotation={[-0.421, 0.167, -0.875]}
        scale={[70.929, 17.064, 56.088]}
      />
      <group
        position={[-112.894, 351.879, -304.305]}
        rotation={[0.114, -0.065, 0.055]}
        scale={1.312}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.M_Staff}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials.M_Effects}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['water-pool-texture-seamless-and-free-thumb36'].geometry}
        material={materials['water-pool-texture-seamless-and-free-thumb36']}
        position={[0, -1034.954, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3460.832}
      />
    </group>
  )
}

useGLTF.preload('./MAIIN4.fbx')

